host: "35.73.90.190"
port: 22
user: "kc-tweb-area"
#user: "bbb"
password: "your_password_here"    # 実際のパスワードを設定してください
#pkey_base64: ""                  # 公開鍵認証は使用しないためコメントアウト
auth_type: "password"            # パスワード認証を使用
#auth_type: "pkey"
proxy_host: "netsp.kirin.co.jp"
proxy_port: 1480
dirs:
#  - "/export/home/www.kirin.co.jp-test-area/"
  - "/tmp/test/"
interval: 60
